const KEY='calsi_podcasts_v1';
const SETTINGS='calsi_podcast_settings_v1';
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>`pod_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const examOne=`Welcome to your Psychology Exam One review. This episode is built to help you hear the ideas as connected concepts instead of isolated flashcards.

Start with the scientific method. Psychology uses a systematic and ethical process to collect and analyze data about behavior. Researchers begin with a broad theory, review previous research, create a specific hypothesis, operationalize the variables, choose a method, collect data, analyze the results, interpret them carefully, and then rely on replication. A theory is a broad explanation. A hypothesis is a specific, testable prediction. A literature review tells you what earlier researchers already found and helps identify gaps. An operational definition explains exactly how a variable will be measured or manipulated.

Psychological science has four major goals: describe, predict, control, and explain behavior. Determinism is the assumption that behavior has enough regularity for prediction to be possible. Psychology is different from some so-called hard sciences because human behavior varies by age, culture, situation, and time. That means psychologists are cautious about claiming that a finding is permanently proven. Replication matters because a result should appear again across studies, samples, and settings.

Ethics are central. Institutional Review Boards, or IRBs, protect research participants. Important protections include privacy, confidentiality, informed consent, and protection from harm. Vulnerable groups such as minors require additional care. Past harmful research helped lead to stricter ethical oversight.

Now think about quality of research. Standardization means participants in the same condition receive the same instructions, timing, dose, and procedure. Reliability means consistency. Validity means measuring what you actually intend to measure. A double-blind study keeps both participants and the people administering the condition from knowing who is in which group, reducing expectancy and bias. Random assignment places participants into groups by chance and helps balance known and unknown participant differences. A common significance threshold is p equals point zero five, which corresponds to about a five percent false-positive risk. Because single studies can be wrong, replication is essential.

There are three major research designs. Experimental research manipulates an independent variable and measures a dependent variable, allowing the strongest causal conclusions when the design is controlled well. Correlational research measures variables as they naturally occur and looks at relationships, but correlation does not prove causation. Descriptive research observes, records, interviews, or studies cases to describe what is happening without establishing cause and effect.

In an experiment, the independent variable, or IV, is what the researcher manipulates. The dependent variable, or DV, is what the researcher measures. The experimental group gets the active treatment. The control group provides a comparison. A placebo is a simulated treatment that controls for expectation effects. In the Botox and self-esteem example, injection type, Botox versus saline, is the independent variable. Self-esteem after treatment is the dependent variable. Saline is a stronger control than no injection because it matches the experience of receiving an injection and controls for placebo and expectancy effects.

Extraneous or confounding variables are other factors that could affect the dependent variable. Age, baseline self-esteem, sleep, previous caffeine use, body-image problems, addiction severity, peer influence, or family history can all become confounds depending on the study. Researchers control these through random assignment, standardization, matching, exclusion criteria, measurement, and statistical controls. If confounds are not controlled, researchers may incorrectly attribute an outcome to the independent variable.

Correlation coefficients range from negative one point zero zero to positive one point zero zero. The absolute value shows strength. The sign shows direction. A positive correlation means the variables move in the same direction. A negative correlation means they move in opposite directions. Even a strong correlation does not establish causation because reverse causation and third variables remain possible.

Descriptive methods include naturalistic observation, interviews, and case studies. Naturalistic observation records behavior in real settings. Interviews can provide rich detail but may be affected by social desirability. Case studies give deep information about one person or a small case but do not generalize well. Descriptive work is useful for generating hypotheses that can later be tested with correlational or experimental designs.

Now switch to neural communication. The nervous system is the biological basis of thought, emotion, and behavior. Neurons communicate through electrical activity within a neuron and chemical communication between neurons. A useful phrase is: electrical within, chemical between.

Know the major parts of a neuron. Dendrites receive incoming chemical messages at receptor sites. The soma, or cell body, contains the nucleus and integrates incoming signals. The axon carries the action potential away from the soma. Terminal buttons are at the end of the axon and contain vesicles filled with neurotransmitters. The synapse is the tiny gap between the sending neuron and the receiving neuron. The presynaptic neuron sends the message. The postsynaptic neuron receives it.

Neurotransmitters are chemical messengers. Vesicles release them into the synapse. They cross the gap and bind to matching receptor sites, often described using a lock-and-key analogy. A neurotransmitter must fit the correct receptor. The major phases can be remembered as transmission, reception, integration, and conduction. Transmission is neurotransmitter release. Reception is binding to receptors. Integration occurs when the soma combines excitatory and inhibitory input. Conduction occurs when an action potential travels down the axon.

An action potential is the neuron's electrical impulse. At rest, the neuron is around negative seventy millivolts. If stimulation pushes it to threshold, around negative fifty-five millivolts, it fires. During the action potential the charge can rise to about positive forty millivolts. The all-or-none law means the neuron either fires a full action potential after reaching threshold or does not fire one. Immediately after firing, the neuron enters a refractory period when it cannot fire again. Its charge may briefly fall below resting potential, for example near negative ninety millivolts, before returning to rest.

The action potential triggers chemical transmission. The electrical impulse travels down the axon to the terminal buttons. Vesicles release neurotransmitters. The neurotransmitters cross the synapse and bind to receptors on the postsynaptic neuron. Those signals then influence whether the next neuron reaches threshold. Afterward, the synapse must be cleaned up.

There are two major cleanup processes. Reuptake means the presynaptic neuron reabsorbs leftover neurotransmitters so they can be reused. Degradation means enzymes break down neurotransmitters in the synapse. Reuptake recycles; degradation destroys. Selective serotonin reuptake inhibitors, or SSRIs, block some serotonin reuptake, leaving serotonin in the synapse longer and increasing its opportunity to act.

Agonists increase or imitate a neurotransmitter's effect or increase the likelihood of neural activity. Antagonists block or reduce a neurotransmitter's effect, often by occupying receptor sites. Narcan acts as an opioid antagonist by blocking opioid receptors. The distinction matters because many psychoactive drugs work by either enhancing or blocking neurotransmitter systems.

Know the major neurotransmitters. Acetylcholine is associated with muscle control, memory, and learning. Serotonin is associated with emotional states and impulse control. Dopamine is linked to reward, motivation, and motor control. Norepinephrine is linked to arousal and alertness. GABA is the primary inhibitory neurotransmitter. Glutamate is the primary excitatory neurotransmitter. Endorphins are associated with pain reduction and reward or pleasure. Neurotransmitter imbalances can influence mood, thought, and behavior.

Glial cells support neurons. Myelin is a fatty sheath around axons that increases the speed and reliability of signal conduction. White matter contains many myelinated axons. Multiple sclerosis, or MS, damages myelin, which slows or disrupts neural communication and can cause movement and cognitive problems. This demonstrates the principle that structure affects function.

Neural networks change with experience. The phrase fire together, wire together means repeated co-activation strengthens connections between neurons. Repetition makes a thought or behavior easier to activate in the future. This helps explain learning, habits, skill development, and why practice improves performance. Disuse weakens performance, while previous learning can make relearning faster.

Connect everything. Experimental design is about isolating cause and effect. Random assignment, placebos, blinding, and control of confounds protect that goal. Correlational designs are useful when manipulation is unethical or impossible, but they only show association. Descriptive methods tell us what is happening and often lead to new hypotheses. In neuroscience, sufficient stimulation pushes a neuron to threshold, an action potential travels down the axon, neurotransmitters are released, receptors receive them, and reuptake or degradation resets the synapse. Psychological experience depends on these biological systems.

For exam practice, make sure you can do more than recognize definitions. Given a new scenario, identify the IV, DV, control group, experimental group, placebo, and possible confounds. Explain why correlation does not equal causation. Compare experimental, correlational, and descriptive designs. Explain reliability versus validity, theory versus hypothesis, reuptake versus degradation, and agonist versus antagonist. Walk through neural communication in order without looking at notes. Explain threshold, all-or-none, refractory period, myelin, MS, SSRIs, and fire together wire together. If you can explain those ideas in your own words and apply them to new examples, you are studying at the level the exam is likely to require.`;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[];}catch{return[];}}
function save(p){localStorage.setItem(KEY,JSON.stringify(p));}
function getSettings(){try{return{rate:1,pitch:1,voice:'',...JSON.parse(localStorage.getItem(SETTINGS)||'{}')}}catch{return{rate:1,pitch:1,voice:''}}}
function saveSettings(s){localStorage.setItem(SETTINGS,JSON.stringify(s));}
let podcasts=load();if(!podcasts.length){podcasts=[{id:uid(),title:'Psychology Exam One',description:'Research methods, scientific thinking, and neural communication review.',text:examOne,createdAt:new Date().toISOString()}];save(podcasts);}
let current=null,index=0,segments=[],paused=false;
function splitText(text){return text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).flatMap(p=>p.length>900?(p.match(/.{1,850}(?:[.!?]\s|$)/g)||[p]):[p]);}
function stop(){speechSynthesis.cancel();current=null;paused=false;}
function speakSegment(){if(!current||index>=segments.length){stop();renderPlayer();return;}const u=new SpeechSynthesisUtterance(segments[index]);const s=getSettings(),voices=speechSynthesis.getVoices();u.rate=Number(s.rate)||1;u.pitch=Number(s.pitch)||1;if(s.voice){const v=voices.find(v=>v.name===s.voice);if(v)u.voice=v;}u.onend=()=>{if(!paused&&current){index++;speakSegment();renderPlayer();}};u.onerror=()=>{};speechSynthesis.speak(u);renderPlayer();}
function play(p,start=0){stop();current=p;segments=splitText(p.text);index=Math.min(start,segments.length-1);speakSegment();}
function togglePause(){if(!current)return;if(speechSynthesis.paused){speechSynthesis.resume();paused=false;}else{speechSynthesis.pause();paused=true;}renderPlayer();}
function jump(n){if(!current)return;speechSynthesis.cancel();index=Math.max(0,Math.min(segments.length-1,index+n));paused=false;speakSegment();}
function nav(){const d=document.querySelector('#desktopNav');if(d&&!d.querySelector('[data-podcast-open]')){const wrap=document.createElement('div');wrap.className='desktop-podcast-nav';wrap.innerHTML='<button class="nav-item" data-podcast-open><span class="nav-icon">🎧</span>Podcast</button>';d.append(wrap);}if(!document.querySelector('.podcast-launch')){const b=document.createElement('button');b.className='podcast-launch';b.title='Podcast mode';b.textContent='🎧';document.body.append(b);b.onclick=open;}document.querySelectorAll('[data-podcast-open]').forEach(b=>b.onclick=open);}
function open(){stop();document.querySelector('#pageTitle').textContent='Podcast';document.querySelector('#pageEyebrow').textContent='COURSEFLOW';document.querySelector('#view').innerHTML='<div class="podcast-page" id="podcastPage"></div>';render();window.scrollTo({top:0,behavior:'smooth'});}
function render(){const root=document.querySelector('#podcastPage');if(!root)return;root.innerHTML=`<section class="card podcast-hero"><div><div class="eyebrow">PODCAST MODE</div><h2>Listen to your study material</h2><p class="muted">Paste notes or a study script, save it as an episode, then have your browser read it aloud.</p></div><button class="primary-btn" id="newPodcast">+ New podcast</button></section><div class="podcast-grid"><div><div class="podcast-list">${podcasts.map(p=>`<article class="card podcast-card"><div><h3>${esc(p.title)}</h3><p class="muted">${esc(p.description||'Study podcast')}</p></div><div class="podcast-card-actions"><button class="primary-btn" data-play="${p.id}">▶ Listen</button><button class="ghost-btn" data-edit="${p.id}">Edit</button><button class="danger-btn" data-delete="${p.id}">Delete</button></div></article>`).join('')}</div></div><aside class="card podcast-player" id="podcastPlayer"></aside></div>`;root.querySelector('#newPodcast').onclick=()=>editor();root.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const p=podcasts.find(x=>x.id===b.dataset.play);play(p);});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor(podcasts.find(x=>x.id===b.dataset.edit)));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this podcast?')){podcasts=podcasts.filter(x=>x.id!==b.dataset.delete);save(podcasts);render();}});renderPlayer();}
function renderPlayer(){const el=document.querySelector('#podcastPlayer');if(!el)return;const voices=speechSynthesis.getVoices(),s=getSettings(),pct=current&&segments.length?Math.round((index/segments.length)*100):0;el.innerHTML=`<div class="podcast-now">Now playing</div><div class="podcast-title">${esc(current?.title||'Nothing playing')}</div><div class="subtle">${current?`Part ${Math.min(index+1,segments.length)} of ${segments.length}`:'Choose an episode to start listening.'}</div><div class="podcast-progress"><div style="width:${pct}%"></div></div><div class="podcast-controls"><button class="ghost-btn" id="prevSeg">↶</button><button class="primary-btn" id="pausePod">${paused?'▶':'Ⅱ'}</button><button class="ghost-btn" id="stopPod">■</button><button class="ghost-btn" id="nextSeg">↷</button><button class="ghost-btn" id="restartPod">↺</button></div><div class="podcast-settings"><label class="field"><span>Voice</span><select id="podVoice">${voices.map(v=>`<option ${v.name===s.voice?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label class="field"><span>Speed: <b id="speedLabel">${s.rate}x</b></span><input id="podRate" type="range" min="0.65" max="1.6" step="0.05" value="${s.rate}"></label><label class="field"><span>Pitch: <b>${s.pitch}</b></span><input id="podPitch" type="range" min="0.7" max="1.3" step="0.05" value="${s.pitch}"></label></div>${current?`<div class="divider"></div><div class="podcast-transcript">${segments.map((x,i)=>`<div class="${i===index?'podcast-segment-active':''}">${esc(x)}</div><br>`).join('')}</div>`:''}`;el.querySelector('#pausePod').onclick=togglePause;el.querySelector('#stopPod').onclick=()=>{stop();renderPlayer();};el.querySelector('#prevSeg').onclick=()=>jump(-1);el.querySelector('#nextSeg').onclick=()=>jump(1);el.querySelector('#restartPod').onclick=()=>current&&play(current,0);const update=()=>{const ns={voice:el.querySelector('#podVoice').value,rate:el.querySelector('#podRate').value,pitch:el.querySelector('#podPitch').value};saveSettings(ns);el.querySelector('#speedLabel').textContent=`${ns.rate}x`;};el.querySelector('#podVoice').onchange=update;el.querySelector('#podRate').oninput=update;el.querySelector('#podPitch').oninput=update;}
function editor(p=null){const old=document.querySelector('.podcast-editor-modal');if(old)old.remove();const w=document.createElement('div');w.className='modal-backdrop podcast-editor-modal';w.innerHTML=`<div class="modal wide podcast-editor"><div class="modal-head"><strong>${p?'Edit':'New'} podcast</strong><button class="icon-btn" data-close>×</button></div><div class="modal-body"><div class="form-grid"><label class="field"><span>Title</span><input class="input" id="podTitle" value="${esc(p?.title||'')}"></label><label class="field"><span>Description</span><input class="input" id="podDesc" value="${esc(p?.description||'')}"></label><label class="field span-2"><span>Podcast text</span><textarea id="podText" placeholder="Paste the study material you want read aloud...">${esc(p?.text||'')}</textarea></label></div></div><div class="modal-foot"><button class="ghost-btn" data-close>Cancel</button><button class="primary-btn" id="savePod">Save podcast</button></div></div>`;document.body.append(w);w.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>w.remove());w.querySelector('#savePod').onclick=()=>{const title=w.querySelector('#podTitle').value.trim(),text=w.querySelector('#podText').value.trim();if(!title||!text)return alert('Add a title and podcast text.');if(p){p.title=title;p.description=w.querySelector('#podDesc').value.trim();p.text=text;p.updatedAt=new Date().toISOString();}else podcasts.unshift({id:uid(),title,description:w.querySelector('#podDesc').value.trim(),text,createdAt:new Date().toISOString()});save(podcasts);w.remove();render();};}
nav();new MutationObserver(nav).observe(document.body,{childList:true,subtree:true});speechSynthesis.onvoiceschanged=()=>renderPlayer();