const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const now=()=>new Date().toISOString();
const cls=(s,id)=>s.classes.find(c=>c.id===id)||s.classes[0];
const live=s=>(s.studySets||[]).filter(x=>!x.deletedAt);
const attempts=t=>(+t.correctCount||0)+(+t.wrongCount||0);
const missRate=t=>attempts(t)?(+t.wrongCount||0)/attempts(t):0;
const troubleScore=t=>(+t.wrongCount||0)*3-(+t.correctCount||0);
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);

function newTerm(term,definition){return{id:uid('term'),term,definition,known:false,favorite:false,correctCount:0,wrongCount:0,lastAnsweredAt:null};}
function norm(t){return{...newTerm(t?.term||'',t?.definition||''),...t,known:!!t?.known,favorite:!!t?.favorite,correctCount:+t?.correctCount||0,wrongCount:+t?.wrongCount||0};}
function parsePairs(text){return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).filter(x=>!x.startsWith('@class')).map(line=>{let p;if(line.includes('|'))p=line.split('|');else if(line.includes('\t'))p=line.split('\t');else if(line.includes('::'))p=line.split('::');else if(line.includes(' - '))p=line.split(' - ');else return null;const term=(p.shift()||'').trim(),definition=p.join(' | ').trim();return term&&definition?newTerm(term,definition):null;}).filter(Boolean);}
function classOptions(state,selected){return state.classes.map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('');}

function modal(title,body,onSave=null,saveLabel='Save',extra=''){
  const w=document.createElement('div');w.className='modal-backdrop study-modal-backdrop';
  w.innerHTML=`<div class="modal wide"><div class="modal-head"><strong>${esc(title)}</strong><button class="icon-btn" data-close>×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${extra}<button class="ghost-btn" data-close>Cancel</button>${onSave?`<button class="primary-btn" data-save>${esc(saveLabel)}</button>`:''}</div></div>`;
  document.body.append(w);const close=()=>w.remove();w.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);w.onclick=e=>{if(e.target===w)close();};w.querySelector('[data-save]')?.addEventListener('click',()=>onSave(w,close));return w;
}

function allTerms(state){return live(state).flatMap(set=>(set.terms||[]).map(term=>({set,term:norm(term)})));}
function trouble(state){return allTerms(state).filter(x=>x.term.wrongCount>0).sort((a,b)=>troubleScore(b.term)-troubleScore(a.term)||missRate(b.term)-missRate(a.term));}
function favorites(state){return allTerms(state).filter(x=>x.term.favorite);}
function insightRow(x,fav=false){const n=attempts(x.term),rate=n?Math.round(missRate(x.term)*100):0;return `<div class="study-insight-row"><div><strong>${esc(x.term.term)}</strong><div class="subtle">${esc(x.set.title)}</div></div><div class="study-insight-meta">${fav?'★':`${x.term.wrongCount} wrong · ${rate}%`}</div></div>`;}

export function renderStudy(root,state,ctx){
  state.studySets||=[];state.ui||={};
  const set=live(state).find(s=>s.id===state.ui.studySetId);if(set)return renderSet(root,state,set,ctx);
  const sets=live(state),bad=trouble(state),favs=favorites(state);
  const cards=sets.map(s=>{const c=cls(state,s.classId),wrong=(s.terms||[]).reduce((n,t)=>n+(+t.wrongCount||0),0);return `<article class="card study-set-card hover" data-open="${s.id}" style="--class-color:${c.color}"><div class="class-topline"></div><div class="study-set-top"><span class="study-class-pill">${esc(c.icon||'📚')} ${esc(c.name)}</span><span class="subtle">${s.terms?.length||0} terms</span></div><h3>${esc(s.title)}</h3><p class="muted">${esc(s.description||'No description')}</p><div class="study-set-stats"><span>★ ${(s.terms||[]).filter(t=>t.favorite).length}</span><span>${wrong} wrong</span></div><div class="study-set-actions"><button class="ghost-btn" data-flash="${s.id}">Flashcards</button><button class="primary-btn" data-quiz="${s.id}">Quiz</button></div></article>`}).join('');
  root.innerHTML=`<section class="study-hero card"><div><div class="eyebrow">STUDY</div><h2>Study sets</h2><p class="muted">CALSI now remembers what you miss, what you favorite, and your edits across synced devices.</p></div><div class="study-hero-actions"><button id="studyBulk" class="ghost-btn">Bulk import</button><button id="studyNew" class="primary-btn">+ New study set</button></div></section><div class="study-insights mt-16"><section class="card study-insight"><div class="card-title-row"><div><div class="card-title">Needs work</div><div class="subtle">Your most-missed questions</div></div><span class="pill"><strong>${bad.length}</strong></span></div>${bad.length?`<div class="study-insight-list">${bad.slice(0,5).map(x=>insightRow(x)).join('')}</div><button id="studyBad" class="ghost-btn full mt-16">Study most missed</button>`:'<div class="subtle">Take a quiz and missed questions will appear here.</div>'}</section><section class="card study-insight"><div class="card-title-row"><div><div class="card-title">Favorites</div><div class="subtle">Saved questions and answers</div></div><span class="pill"><strong>${favs.length}</strong></span></div>${favs.length?`<div class="study-insight-list">${favs.slice(0,5).map(x=>insightRow(x,true)).join('')}</div><button id="studyFav" class="ghost-btn full mt-16">Study favorites</button>`:'<div class="subtle">Star a question to save it here.</div>'}</section></div><div class="study-grid mt-16">${cards||`<div class="card study-empty"><h3>No study sets yet</h3><p class="muted">Create one manually or bulk paste terms and definitions.</p><button id="studyEmptyNew" class="primary-btn">Create your first set</button></div>`}</div>`;
  const open=(id,mode='overview')=>{state.ui.studySetId=id;state.ui.studyMode=mode;delete state.ui.studyFocus;ctx.persist(false);renderStudy(root,state,ctx);};
  root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));root.querySelectorAll('[data-flash]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(b.dataset.flash,'flashcards');});root.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(b.dataset.quiz,'quiz');});
  (root.querySelector('#studyNew')||root.querySelector('#studyEmptyNew'))?.addEventListener('click',()=>editor(state,null,{...ctx,rerender:()=>renderStudy(root,state,ctx)}));root.querySelector('#studyBulk')?.addEventListener('click',()=>bulk(state,{...ctx,rerender:()=>renderStudy(root,state,ctx)}));root.querySelector('#studyBad')?.addEventListener('click',()=>mixed(root,state,'bad',ctx));root.querySelector('#studyFav')?.addEventListener('click',()=>mixed(root,state,'fav',ctx));
}

function renderSet(root,state,set,ctx){
  set.terms=(set.terms||[]).map(norm);const c=cls(state,set.classId),mode=state.ui.studyMode||'overview',bad=set.terms.filter(t=>t.wrongCount>0).sort((a,b)=>troubleScore(b)-troubleScore(a)),favs=set.terms.filter(t=>t.favorite);
  root.innerHTML=`<div class="study-set-header"><button id="back" class="ghost-btn">← All sets</button><div class="study-set-heading"><span class="study-class-pill" style="--class-color:${c.color}">${esc(c.icon||'📚')} ${esc(c.name)}</span><h2>${esc(set.title)}</h2><span class="subtle">${set.terms.length} terms · ${favs.length} favorites · ${bad.length} missed</span></div><div class="study-header-actions"><button id="edit" class="ghost-btn">Edit set</button><button id="delete" class="danger-btn">Delete</button></div></div><div class="segmented study-tabs"><button data-mode="overview" class="${mode==='overview'?'active':''}">Terms</button><button data-mode="flashcards" class="${mode==='flashcards'?'active':''}">Flashcards</button><button data-mode="quiz" class="${mode==='quiz'?'active':''}">Quiz</button></div><div class="study-focus-actions mt-16">${bad.length?'<button id="badSet" class="ghost-btn">Study missed most</button>':''}${favs.length?'<button id="favSet" class="ghost-btn">Study favorites</button>':''}</div><div id="studyBody" class="mt-16"></div>`;
  root.querySelector('#back').onclick=()=>{state.ui.studySetId=null;state.ui.studyMode='overview';delete state.ui.studyFocus;ctx.persist(false);renderStudy(root,state,ctx);};root.querySelector('#edit').onclick=()=>editor(state,set.id,{...ctx,rerender:()=>renderStudy(root,state,ctx)});root.querySelector('#delete').onclick=()=>removeSet(root,state,set,ctx);root.querySelector('#badSet')?.addEventListener('click',()=>{state.ui.studyMode='quiz';state.ui.studyFocus='bad';ctx.persist(false);renderStudy(root,state,ctx);});root.querySelector('#favSet')?.addEventListener('click',()=>{state.ui.studyMode='flashcards';state.ui.studyFocus='fav';ctx.persist(false);renderStudy(root,state,ctx);});root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.ui.studyMode=b.dataset.mode;delete state.ui.studyFocus;ctx.persist(false);renderStudy(root,state,ctx);});
  let terms=set.terms;if(state.ui.studyFocus==='bad')terms=bad;if(state.ui.studyFocus==='fav')terms=favs;const body=root.querySelector('#studyBody');if(mode==='flashcards')flashcards(body,set,terms,ctx);else if(mode==='quiz')quiz(body,set,terms,ctx);else termsView(body,set,ctx);
}

function termsView(root,set,ctx){root.innerHTML=`<div class="study-term-list">${set.terms.map((t,i)=>{const n=attempts(t),rate=n?Math.round(missRate(t)*100):0;return `<article class="card study-term-row"><span class="study-term-number">${i+1}</span><div><div class="study-term-label">TERM</div><strong>${esc(t.term)}</strong><div class="study-term-stats">${t.wrongCount} wrong · ${t.correctCount} right${n?` · ${rate}% miss`:''}</div></div><div><div class="study-term-label">DEFINITION</div><span>${esc(t.definition)}</span></div><button class="favorite-btn ${t.favorite?'active':''}" data-star="${t.id}" title="Favorite">★</button></article>`}).join('')}</div>`;root.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{const t=set.terms.find(x=>x.id===b.dataset.star);t.favorite=!t.favorite;set.updatedAt=now();ctx.persist();termsView(root,set,ctx);});}

function flashcards(root,set,terms,ctx){if(!terms.length){root.innerHTML='<div class="card">No cards match this study mode yet.</div>';return;}let order=[...terms],i=0,flip=false;const draw=()=>{const t=order[i];root.innerHTML=`<section class="study-session"><div class="study-progress"><span>${i+1} / ${order.length}</span><div class="progress-track"><div class="progress-bar" style="width:${(i+1)/order.length*100}%"></div></div></div><div class="flashcard-toolbar"><button id="star" class="favorite-btn ${t.favorite?'active':''}">★</button><span class="subtle">${t.wrongCount} wrong · ${t.correctCount} right</span></div><button id="card" class="flashcard ${flip?'flipped':''}"><div class="flashcard-face"><div class="study-term-label">${flip?'DEFINITION':'TERM'}</div><div class="flashcard-text">${esc(flip?t.definition:t.term)}</div><div class="subtle">Click to flip</div></div></button><div class="flash-controls"><button id="prev" class="ghost-btn">← Previous</button><button id="shuffle" class="ghost-btn">Shuffle</button><button id="known" class="ghost-btn">${t.known?'✓ Known':'Mark known'}</button><button id="next" class="primary-btn">Next →</button></div></section>`;root.querySelector('#card').onclick=()=>{flip=!flip;draw();};root.querySelector('#prev').onclick=()=>{i=(i-1+order.length)%order.length;flip=false;draw();};root.querySelector('#next').onclick=()=>{i=(i+1)%order.length;flip=false;draw();};root.querySelector('#shuffle').onclick=()=>{order=shuffle(order);i=0;flip=false;draw();};root.querySelector('#known').onclick=()=>{t.known=!t.known;set.updatedAt=now();ctx.persist();draw();};root.querySelector('#star').onclick=()=>{t.favorite=!t.favorite;set.updatedAt=now();ctx.persist();draw();};};draw();}

function quiz(root,set,terms,ctx){if(terms.length<2){root.innerHTML='<div class="card">At least 2 questions are needed for this quiz.</div>';return;}let qs=shuffle([...terms]),i=0,score=0,answered=false,missed=[];const draw=()=>{if(i>=qs.length){const pct=Math.round(score/qs.length*100);root.innerHTML=`<section class="card quiz-results"><div class="eyebrow">QUIZ COMPLETE</div><div class="quiz-score">${pct}%</div><h2>${score} of ${qs.length} correct</h2><p class="muted">${missed.length?`${missed.length} missed question${missed.length===1?'':'s'} saved to Needs work.`:'No misses this round.'}</p><div class="study-set-actions"><button id="again" class="primary-btn">Study again</button>${missed.length>1?'<button id="missed" class="ghost-btn">Quiz missed questions</button>':''}</div></section>`;root.querySelector('#again').onclick=()=>{qs=shuffle([...terms]);i=0;score=0;missed=[];answered=false;draw();};root.querySelector('#missed')?.addEventListener('click',()=>{qs=shuffle([...missed]);i=0;score=0;missed=[];answered=false;draw();});return;}const q=qs[i],choices=shuffle([q,...shuffle(set.terms.filter(t=>t.id!==q.id)).slice(0,3)]);root.innerHTML=`<section class="study-session"><div class="study-progress"><span>Question ${i+1} of ${qs.length}</span><span>${score} correct</span></div><article class="card quiz-question"><div class="quiz-question-top"><div class="study-term-label">CHOOSE THE DEFINITION</div><button id="star" class="favorite-btn ${q.favorite?'active':''}">★</button></div><h2>${esc(q.term)}</h2><div class="study-term-stats">${q.wrongCount} wrong · ${q.correctCount} right</div></article><div class="quiz-options">${choices.map(ch=>`<button class="quiz-option" data-answer="${ch.id}">${esc(ch.definition)}</button>`).join('')}</div><div id="feedback"></div></section>`;root.querySelector('#star').onclick=()=>{q.favorite=!q.favorite;set.updatedAt=now();ctx.persist();draw();};root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const ok=b.dataset.answer===q.id;if(ok){score++;q.correctCount++;}else{q.wrongCount++;missed.push(q);}q.lastAnsweredAt=now();set.updatedAt=now();ctx.persist();root.querySelectorAll('[data-answer]').forEach(x=>{if(x.dataset.answer===q.id)x.classList.add('correct');else if(x===b)x.classList.add('wrong');x.disabled=true;});root.querySelector('#feedback').innerHTML=`<div class="quiz-feedback ${ok?'correct-text':'wrong-text'}"><strong>${ok?'Correct':'Not quite'}</strong><span>${ok?'Nice work.':`Correct answer: ${esc(q.definition)}`}</span><button id="continue" class="primary-btn">Continue</button></div>`;root.querySelector('#continue').onclick=()=>{i++;answered=false;draw();};});};draw();}

function editor(state,setId,ctx){const existing=live(state).find(s=>s.id===setId),s=existing||{id:uid('set'),title:'',description:'',classId:state.classes[0]?.id||'general',terms:[],createdAt:now(),updatedAt:now()};const text=(s.terms||[]).map(t=>`${t.term} | ${t.definition}`).join('\n');modal(existing?'Edit study set':'New study set',`<div class="form-grid"><div class="field span-2"><label>Set title</label><input id="title" class="input" value="${esc(s.title)}"></div><div class="field"><label>Class</label><select id="class">${classOptions(state,s.classId)}</select></div><div class="field"><label>Description</label><input id="desc" class="input" value="${esc(s.description||'')}"></div><div class="field span-2"><label>Terms — one per line</label><textarea id="terms" style="min-height:280px">${esc(text)}</textarea><div class="subtle">Term | Definition. Quiz history and favorites are preserved when you edit.</div></div></div>`,(w,close)=>{const title=w.querySelector('#title').value.trim(),parsed=parsePairs(w.querySelector('#terms').value);if(!title)return ctx.toast('Give the study set a title');if(!parsed.length)return ctx.toast('Add at least one term and definition');const old=(s.terms||[]).map(norm),exact=new Map(old.map(t=>[`${t.term}|||${t.definition}`,t])),byTerm=new Map(old.map(t=>[t.term,t]));parsed.forEach(t=>{const o=exact.get(`${t.term}|||${t.definition}`)||byTerm.get(t.term);if(o)Object.assign(t,{id:o.id,known:o.known,favorite:o.favorite,correctCount:o.correctCount,wrongCount:o.wrongCount,lastAnsweredAt:o.lastAnsweredAt});});const next={...s,title,classId:w.querySelector('#class').value,description:w.querySelector('#desc').value.trim(),terms:parsed,updatedAt:now(),deletedAt:null};if(existing)state.studySets=state.studySets.map(x=>x.id===setId?next:x);else state.studySets.push(next);ctx.persist();close();ctx.rerender();ctx.toast(existing?'Study set updated and synced':'Study set created');});}

function removeSet(root,state,set,ctx){const w=modal('Delete study set?',`<p class="muted">Delete <strong>${esc(set.title)}</strong>? This deletion will sync to your other devices.</p>`,null,'','<button id="confirmDelete" class="danger-btn" style="margin-right:auto">Delete set</button>');w.querySelector('#confirmDelete').onclick=()=>{const stamp=now();set.deletedAt=stamp;set.updatedAt=stamp;state.ui.studySetId=null;state.ui.studyMode='overview';delete state.ui.studyFocus;ctx.persist();w.remove();ctx.toast('Study set deleted');renderStudy(root,state,ctx);};}

function bulk(state,ctx){modal('Bulk import study set',`<div class="form-grid"><div class="field"><label>Set title</label><input id="title" class="input"></div><div class="field"><label>Class</label><select id="class">${classOptions(state,state.classes[0]?.id)}</select></div><div class="field span-2"><label>Paste terms</label><textarea id="terms" style="min-height:300px"></textarea><div class="subtle">Accepted separators: |, tab, ::, or “ - ”.</div></div></div>`,(w,close)=>{const title=w.querySelector('#title').value.trim(),terms=parsePairs(w.querySelector('#terms').value);if(!title)return ctx.toast('Give the study set a title');if(!terms.length)return ctx.toast('No term/definition pairs found');state.studySets.push({id:uid('set'),title,classId:w.querySelector('#class').value,description:'',terms,createdAt:now(),updatedAt:now(),deletedAt:null});ctx.persist();close();ctx.rerender();ctx.toast(`${terms.length} terms imported`);},'Import set');}

function mixed(root,state,kind,ctx){const items=kind==='fav'?favorites(state):trouble(state).slice(0,30);if(items.length<2)return ctx.toast(kind==='fav'?'Favorite at least 2 questions first':'Miss at least 2 questions first');const temp={id:'mixed',title:kind==='fav'?'Favorite questions':'Most missed questions',classId:'general',terms:items.map(x=>x.term)};root.innerHTML=`<div class="study-set-header"><button id="back" class="ghost-btn">← Study</button><div class="study-set-heading"><div class="eyebrow">FOCUSED STUDY</div><h2>${esc(temp.title)}</h2><span class="subtle">${temp.terms.length} questions across your study sets</span></div></div><div class="segmented study-tabs"><button id="flash">Flashcards</button><button id="quiz" class="active">Quiz</button></div><div id="body" class="mt-16"></div>`;const body=root.querySelector('#body'),save=()=>{items.forEach(x=>x.set.updatedAt=now());ctx.persist();},q=()=>{root.querySelector('#quiz').classList.add('active');root.querySelector('#flash').classList.remove('active');quiz(body,temp,temp.terms,{...ctx,persist:save});},f=()=>{root.querySelector('#flash').classList.add('active');root.querySelector('#quiz').classList.remove('active');flashcards(body,temp,temp.terms,{...ctx,persist:save});};root.querySelector('#back').onclick=()=>renderStudy(root,state,ctx);root.querySelector('#quiz').onclick=q;root.querySelector('#flash').onclick=f;q();}
